spring.application.name=taco-cloud
spring.datasource.generate-unique-name=false
spring.datasource.name = "taocloud"

logging.level.root=INFO
logging.level.tacos=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=WARN
